developerment:
  SHOPIFY_API_KEY: ''
  SHOPIFY_API_SECRET: ''
  SHOPIFY_APP_DOMAIN: '' #no trailing slash
  GMAIL_USERNAME: ''
  GMAIL_PASSWORD: ''
  DATABASE_NAME: ''
  DATABASE_USER: ''
  DATABASE_PASSWORD: '' #Uncomment in database.yml if you are using for development

production:
  SHOPIFY_API_KEY: ''
  SHOPIFY_API_SECRET: ''
  SHOPIFY_APP_DOMAIN: ''
  GMAIL_USERNAME: ''
  GMAIL_PASSWORD: ''
  DATABASE_NAME: ''
  DATABASE_USER: ''
  DATABASE_PASSWORD: '' #Uncomment in database.yml if you are using for development
